services:
    bruninoit.wvtt.listener:
        class: bruninoit\ajaxreload\event\main_listener
        arguments:
            - @config
            - @request
        tags:
            - { name: event.listener }
